const USER_FACING_DECISION_QUEUE_TERM_REPLACEMENTS: readonly (readonly [RegExp, string])[] = [
  [/유료\s*의향/gu, "돈을 낼 이유"],
  [/지불\s*의향/gu, "돈을 낼 이유"],
  [/가장\s+먼저\s+검증할\s+primary customer/giu, "가장 먼저 검증할 고객/사용자"],
  [/첫\s+Build Slice/giu, "첫 구현 범위"],
  [/\bprimary customer\b/giu, "핵심 고객/사용자"],
  [/\bWhat evidence would resolve\b/giu, "어떤 근거가 판단을 좁힐 수 있는지"],
  [/\bValidate evidence for:\s*/giu, ""],
  [/\bFind decision evidence for:\s*/giu, ""],
  [/\bFind evidence for:\s*/giu, ""],
  [/\bBroaden research beyond existing notes for:\s*/giu, "기존 리서치 메모를 넘어 더 넓게 확인: "],
  [/\bBroaden research for:\s*/giu, "더 넓게 확인: "],
  [/\bcollect wider sources and counter-evidence\b/giu, "더 넓은 출처와 반례를 수집"],
  [/\bcounter-evidence\b/giu, "반례"],
  [/\bMVP Scope\b/gu, "첫 버전 범위"],
  [/\bSuccess Criteria\b/gu, "성공 기준"],
  [/\bValidation Plan\b/gu, "확인 계획"],
  [/\bTarget Customer\b/gu, "첫 고객/사용자"],
  [/\bValue Proposition\b/gu, "사용자가 선택할 이유"],
  [/\bCurrent Alternatives\b/gu, "현재 쓰는 대안"],
  [/\bFounder Brief\b/gu, "창업자 요약"],
  [/\bPlanning Handoff\b/gu, "구현 계획 넘기기"],
  [/\bEvidence Matrix\b/gu, "근거 표"],
  [/\bDifferentiation\b/gu, "차별점"],
  [/\bNon-goals\b/gu, "이번에 하지 않을 일"],
  [/\bvalue proposition\b/giu, "사용자가 선택할 이유"],
  [/\bvalidation plan\b/giu, "확인 계획"],
  [/\binterview target\b/giu, "인터뷰 대상"],
  [/\bpain threshold\b/giu, "불편 기준"],
  [/\bproblem\b/giu, "문제"],
  [/\bacquisition\b/giu, "고객 모집"],
  [/\bhandoff\b/giu, "전달"],
  [/\bevidence\b/giu, "근거"],
  [/\bBuild Slice\b/giu, "구현 범위"],
  [/\bMVP\b/gu, "첫 버전"],
  [/\bretention proxy\b/giu, "반복해서 쓸 만하다는 신호"],
  [/\bfounder\/team\b/giu, "만드는 사람/팀"],
  [/\bfounder\b/giu, "만드는 사람"],
  [/\bcustomer lock-in\b/giu, "고객을 성급하게 확정하는 일"],
  [/\bwillingness-to-pay\b/giu, "돈을 낼 이유"],
  [/\bpaid intent decision\b/giu, "돈을 낼 사람에 대한 판단"],
  [/\bpaid intent\b/giu, "돈을 낼 이유"],
  [/\bDecision Queue burn-down\b/gu, "질문 목록 처리"],
  [/\bNext Validation Action\b/gu, "다음 검증 작업"],
  [/\bvalidation action\b/giu, "검증 작업"],
  [/\bKnown Risk\b/gu, "다음 확인 리스크"],
  [/\blegal\/ops\/security\b/giu, "법무/운영/보안"],
  [/\bprice proxy\b/giu, "가격 확인 방법"],
  [/\bscope creep\b/giu, "범위가 계속 커지는 문제"],
  [/\bresearch_needed\b/giu, "리서치 필요"],
  [/\bhigh-impact gate\b/giu, "중요 검증 기준"],
  [/\bplanning-ready\b/giu, "계획 준비 완료"],
  [/\bSpec section\b/giu, "스펙 항목"],
  [/\bcompletion gate\b/giu, "완성 기준"],
  [/\btradeoff\b/giu, "장단점"],
  [/\bpro\/con\b/giu, "찬반"],
  [/\bproxy\b/giu, "행동 신호"],
  [/\bconcierge\b/giu, "수동 지원"],
  [/\bowner\/date\b/giu, "담당자/날짜"],
  [/\bconfidence\b/giu, "확신도"],
  [/\bpivot\b/giu, "방향 전환"],
  [/\bworkflow는/giu, "작업 흐름은"],
  [/\bworkflow가/giu, "작업 흐름이"],
  [/\bworkflow를/giu, "작업 흐름을"],
  [/\bworkflow와/giu, "작업 흐름과"],
  [/\bworkflow의/giu, "작업 흐름의"],
  [/\bworkflow\b/giu, "작업 흐름"],
  [/\bflow\b/giu, "흐름"],
  [/\bGUI\b/gu, "화면 UI"],
  [/\bCLI\b/gu, "명령어 방식"],
  [/\bdaemon\b/giu, "상시 실행 프로그램"],
  [/\blocal data\b/giu, "내 컴퓨터의 데이터"],
  [/\bsecret\b/giu, "비밀값/토큰"],
  [/\bscope\b/giu, "범위"],
  [/\breadiness\b/giu, "준비 상태"],
  [/\bdecision\b/giu, "판단"],
  [/\bsection\b/giu, "항목"],
  [/\bclaim\b/giu, "주장"]
];

export function plainUserFacingDecisionQueueText(text: string) {
  return USER_FACING_DECISION_QUEUE_TERM_REPLACEMENTS.reduce(
    (current, [pattern, replacement]) => current.replace(pattern, replacement),
    text
  );
}
